Throw loader exception as Error to prevent Angular issues (#446)
Fixes this https://github.com/angular/angular-cli warning:

  Syntax Error: NonErrorEmittedError: (Emitted value instead of an instance of Error)
    Query/mutation names are required for a document with multiple definitions